[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
CI = "1"

# Set the HEDERA_NETWORK to mainnet for production
[context.production.environment]
HEDERA_NETWORK = "mainnet"

# Set the HEDERA_NETWORK to testnet for deployment previews on PRs
[context.deploy-preview.environment]
HEDERA_NETWORK = "testnet"

[[redirects]]
from = "/service-worker.js"
to = "/service-worker.js"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
